# Generated by Django 6.0.3 on 2026-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pri kou a an HTG', max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Koche sa a sèlman si elèv la peye'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(help_text='Lien Youtube la'),
        ),
    ]
