# Generated by Django 6.0.3 on 2026-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_course_price_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='message',
            field=models.TextField(blank=True, help_text='Mesaj oswa referans tranzaksyon elèv la', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Foto prèv peman an', null=True, upload_to='enrollment_proofs/'),
        ),
    ]
