# Generated by Django 6.0.3 on 2026-04-02 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_course_instructor_profile_signature_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montan Peye')),
                ('month', models.DateField(help_text='Chwazi mwa w ap peye a (egz: 01/04/2026)', verbose_name='Pou mwa')),
                ('date_paid', models.DateTimeField(auto_now_add=True, verbose_name='Dat Peman')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course', verbose_name='Kou')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pwofesè')),
            ],
            options={
                'verbose_name': 'Peman Pwofesè',
                'verbose_name_plural': 'Peman Pwofesè yo',
            },
        ),
    ]
