# Generated by Django 6.0.3 on 2026-04-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='month',
            field=models.DateField(help_text='Chwazi mwa w ap peye a (egz: 2026-04-01)', verbose_name='Pou mwa'),
        ),
    ]
