# Generated by Django 6.0.3 on 2026-04-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_alter_payout_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
