# Generated by Django 6.0.3 on 2026-04-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Deskripsyon oswa kontni tèks leson an', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lòd leson an nan kou a (egz: 1, 2, 3...)'),
        ),
    ]
