# Generated by Django 6.0.3 on 2026-05-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_product_serviceoffering_alter_payout_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='seminar',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Lyen ekst?n oubyen paj enskripsyon pou semin? a', null=True),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/items/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='academy.galleryalbum')),
            ],
        ),
    ]
